site_name: Amusement Park Simulation
nav:
  - Home: README.md
  - About: ABOUT.md
  - Algorithms: BERNOULLI_ALGORITHMS.md
  - Types:
    - Numbers: types/NUMBER_TYPE.md
    - Sets: types/BERNOULLI_SETS.md
theme:
  name: mkdocs
