site_name: The concept of Bernoulli types
nav:
  - Home: README.md
  - Algorithm: BERNOULLI_ALGORITHM.md
  - Algebra: BERNOULLI_ALGEBRAS.md
  - Relation: BERNOULLI_RELATION.md
  - "Normal form": NORMAL_FORMS.md
  - Numbers: NUMBER_TYPE.md
  - "Perfect hash filter": PHF.md
  - Values: VALUE.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
